version: "3.8"

services:
  frontend:
    build: gmail-message-reactjs
    ports:
      - "3000:3000"

  backend:
    build: backend-server
    ports:
      - "5000:5000"

  nginx:
    build: .
    ports:
      - "8080:8080"
      - "4000:4000"
